import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "./components/Header";
import Latest from "./components/Latest";
import CoffeeTables from "./components/CoffeeTables";
import Lighting from "./components/Lighting";
import Shelves from "./components/Shelves";
import SideTables from "./components/SideTables";
import Artists from "./components/Artists";
import Gallery from "./components/Gallery";
import Footer from "./components/Footer";

const Home: NextPage = () => {
  return (
    <div className="overflow-hidden">
      <Head>
        <title>Lak Gallery 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Latest />

      <CoffeeTables />

      <Lighting />

      <Shelves />

      <SideTables />

      <Artists />

      <Gallery />

      <Footer />
    </div>
  );
};

export default Home;
